class ProvidersController < ApplicationController
    include ApplicationHelper
    include ActionController::MimeResponds

    # respond only to JSON requests
    respond_to :json
    respond_to :html, only: []
    respond_to :xml, only: []

    # Universal-Registrar "DID Provider" endpoints, storing DIDs in the local
    # repository database instead of publishing them to a remote location.
    #
    # The cryptographic material (DID, document, logs, keys) is generated by the
    # oydid gem with `skip_publish: true`; for update/deactivate the current DID
    # state is supplied to the gem in-process via `local_doc`/`local_log`, and the
    # Client-Managed-Secret-Mode (CMSM) intermediate data is persisted through a
    # `LocalCmsmStore`. The resulting document and log entries are persisted with
    # `local_store_did` (shared with DidsController#create).

    # input
    # {
    #     "options": { ... },
    #     "secret":  { ... },
    #     <document fields for CMSM, e.g. "key_hex": "...">
    # }
    def create
        params.permit!
        options = provider_options
        options[:cmsm_store] = LocalCmsmStore.new

        if options[:cmsm]
            # Client-Managed-Secret-Mode: the client provides the public key (and,
            # in phase 2, a signature); private keys never leave the client.
            doc = params.except(:options, :secret, :provider, :controller, :action)
            doc = JSON.parse(doc.to_json).transform_keys(&:to_sym)
            if !doc[:key_hex].nil?
                doc[:key] = Oydid.multi_encode(["ed01#{doc[:key_hex]}"].pack("H*"), options).first
                doc.delete(:key_hex)
            end
            if !options[:sig].nil?
                doc[:opt] = {:sig => options[:sig]}
                options.delete(:sig)
            end
            if doc[:key].nil?
                render json: {"error": "missing public key in CMSM"},
                       status: 400
                return
            end
            if options[:key_type].nil?
                options[:key_type] = 'p256'
            end
            if options[:key_type] == 'Secp256r1'
                options[:key_type] = 'p256'
            end
        else
            doc = {}
            options[:authentication] = true
            if options[:type] == "ES256"
                options[:key_type] = 'p256'
                options[:keyAgreement] = true
            else
                options[:key_type] = 'ed25519'
                options[:x25519_keyAgreement] = true
            end
        end

        status, msg = Oydid.create(doc, options)

        if status.nil?
            render json: {"error": msg},
                   status: 500
            return
        elsif msg == "cmsm"
            # CMSM phase 1: intermediate data has been persisted by the gem via
            # LocalCmsmStore; return the value the client has to sign
            render json: status,
                   status: 201
            return
        end

        did_hash = local_identifier(status["did"])
        ok, store_msg = local_store_did(did_hash, status["doc"], status["log"])
        if !ok
            render json: {"error": store_msg},
                   status: 500
            return
        end

        retVal = {
            "did": Oydid.percent_encode(status["did"]),
            "controllerKeyId": Oydid.percent_encode(status["did"]) +  '#key-doc',
            "keys": create_keys(status, options),
            "services": []
        }
        render json: retVal.to_json,
               status: 200
    end

    # input
    # {
    #     "args":        { "did": "did:oyd:..." },
    #     "didDocument": { ... },          # optional (client-managed update)
    #     "options":     { ... },
    #     "secret":      { ... }
    # }
    def update
        old_did = params[:args][:did]
        didDocument = params[:didDocument]
        params.permit!
        options = provider_options

        old_doc, old_log = load_local_state(old_did)
        if old_doc.nil?
            render json: {"error": "unknown DID"},
                   status: 404
            return
        end
        options[:local_doc] = old_doc
        options[:local_log] = old_log

        did_obj = JSON.parse((didDocument || {}).to_json) rescue {}
        did_obj = {} if did_obj.nil?
        if did_obj.is_a?(Hash) && did_obj["@context"] == "https://www.w3.org/ns/did/v1"
            did_obj = Oydid.fromW3C(did_obj, options)
        end

        if did_obj.is_a?(Hash) && !did_obj["key"].nil? &&
           !options[:log_revoke].nil? && !options[:log_update].nil? && !options[:log_terminate].nil?
            # client-managed update: caller supplies pre-signed log records
            old_doc_pubkey = old_doc["key"].split(":").first.to_s
            success, vmsg = Oydid.verify(options[:log_update]["doc"], options[:log_update]["sig"], old_doc_pubkey)
            if !success
                render json: {"error": "invalid input data (update log has invalid signature)"},
                       status: 400
                return
            end
            did = "did:oyd:" + Oydid.multi_hash(Oydid.canonical(did_obj), options).first
            logs = [options[:log_revoke], options[:log_update], options[:log_terminate]]
            ok, store_msg = local_store_did(local_identifier(did), did_obj, logs)
            if !ok
                render json: {"error": store_msg},
                       status: 500
                return
            end
            status = {
                "did" => did,
                "doc" => did_obj,
                "log" => logs,
                "private_key" => "",
                "revocation_key" => ""
            }
        else
            status, msg = Oydid.update(did_obj, old_did, options)
            if status.nil?
                render json: {"error": msg},
                       status: 500
                return
            end
            ok, store_msg = local_store_did(local_identifier(status["did"]), status["doc"], status["log"])
            if !ok
                render json: {"error": store_msg},
                       status: 500
                return
            end
        end

        retVal = {
            "did": Oydid.percent_encode(status["did"]),
            "provider": request.base_url,
            "controllerKeyId": Oydid.percent_encode(status["did"]) +  '#key-doc',
            "keys": update_keys(status),
            "services": []
        }
        render json: retVal.to_json,
               status: 200
    end

    # input
    # {
    #     "identifier": { "did": "did:oyd:..." },
    #     "options":    { ... },
    #     "secret":     { ... }
    # }
    def deactivate
        did = params[:identifier][:did]
        params.permit!
        options = provider_options
        if options[:old_doc_pwd].nil? && !options[:doc_pwd].nil?
            options[:old_doc_pwd] = options[:doc_pwd]
        end
        if options[:old_rev_pwd].nil? && !options[:rev_pwd].nil?
            options[:old_rev_pwd] = options[:rev_pwd]
        end

        old_doc, old_log = load_local_state(did)
        if old_doc.nil?
            render json: {"error": "unknown DID"},
                   status: 404
            return
        end
        options[:local_doc] = old_doc
        options[:local_log] = old_log

        if !options[:log_revoke].nil?
            # client-managed deactivation: caller supplies the revocation log
            revoc_log = options[:log_revoke]
        else
            # with skip_publish the gem returns the revocation log entry instead
            # of publishing it, so we can persist it locally
            revoc_log, msg = Oydid.revoke(did, options)
            if revoc_log.nil?
                render json: {"error": msg},
                       status: 500
                return
            end
        end

        ok, store_msg = local_store_did(local_identifier(did), old_doc, [revoc_log])
        if !ok
            render json: {"error": store_msg},
                   status: 500
            return
        end

        render json: {"did": Oydid.percent_encode(did), "success": true}.to_json,
               status: 200
    end

    private

    # build option hash from request, force local in-process storage
    def provider_options
        options = params[:options] || {}
        secret = params[:secret] || {}
        options = options.to_hash.merge(secret.to_hash).transform_keys(&:to_sym)
        options[:return_secrets] = true
        options[:skip_publish] = true
        options
    end

    # strip the "did:oyd:" prefix and any location suffix
    def local_identifier(did)
        (did.to_s.delete_prefix("did:oyd:").split(LOCATION_PREFIX).first rescue did.to_s)
    end

    # resolve current DID document + raw log array from the local database
    def load_local_state(did)
        did_hash = local_identifier(did)
        _did, doc = local_retrieve_document(did_hash)
        return [nil, nil] if doc.nil?
        [doc, local_retrieve_log(did_hash)]
    end

    # build the universal-registrar "keys" array for a freshly created DID
    def create_keys(status, options)
        keys = []
        if options[:type] == "ES256" || options[:key_type] == "p256"
            if !status["private_key"].nil?
                keyJwk = Oydid.private_key_to_jwk(status["private_key"]).first
                keys << {
                    "kid": Oydid.percent_encode(status["did"]) +  '#key-doc',
                    "kms": "local",
                    "type": "ES256",
                    "jwk": keyJwk
                }
            end
        else
            # document key
            code, length, pubKey = Oydid.multi_decode(status["doc"]["key"].split(":").first).first.unpack('CCa*')
            pubKeyHex = pubKey.bytes.pack('C*').unpack1('H*')
            code, length, privKey = Oydid.multi_decode(status["private_key"]).first.unpack('SCa*')
            privKeyHex = privKey.bytes.pack('C*').unpack1('H*')
            keys << {
                "kid": Oydid.percent_encode(status["did"]) +  '#key-doc',
                "kms": "local",
                "type": "Ed25519",
                "publicKeyHex": pubKeyHex,
                "privateKeyHex": privKeyHex + pubKeyHex
            }

            # revocation key
            code, length, pubKey = Oydid.multi_decode(status["doc"]["key"].split(":").last).first.unpack('CCa*')
            pubKeyHex = pubKey.bytes.pack('C*').unpack1('H*')
            code, length, privKey = Oydid.multi_decode(status["revocation_key"]).first.unpack('SCa*')
            privKeyHex = privKey.bytes.pack('C*').unpack1('H*')
            keys << {
                "kid": Oydid.percent_encode(status["did"]) +  '#key-rev',
                "kms": "local",
                "type": "Ed25519",
                "publicKeyHex": pubKeyHex,
                "privateKeyHex": privKeyHex + pubKeyHex
            }

            # x25519 key agreement
            code, length, pubKey = Oydid.multi_decode(status["doc"]["doc"]["keyAgreement"].first[:publicKeyMultibase]).first.unpack('CCa*')
            pubKeyHex = pubKey.bytes.pack('C*').unpack1('H*')
            code, length, privKey = Oydid.multi_decode(status["private_key"]).first.unpack('SCa*')
            privKeyHex = privKey.bytes.pack('C*').unpack1('H*')
            keys << {
                "kid": Oydid.percent_encode(status["did"]) +  '#key-doc-x25519',
                "kms": "local",
                "type": "X25519",
                "publicKeyHex": pubKeyHex,
                "privateKeyHex": privKeyHex + pubKeyHex
            }
        end
        keys
    end

    # build the "keys" array for an updated DID; omits private parts when the
    # private keys are managed by the client (not known to the repository)
    def update_keys(status)
        keys = []
        doc_pub_mb = status["doc"]["key"].split(":").first rescue nil
        rev_pub_mb = status["doc"]["key"].split(":").last rescue nil

        if !doc_pub_mb.nil?
            doc_key = {
                "kid": Oydid.percent_encode(status["did"]) +  '#key-doc',
                "kms": "local",
                "type": "Ed25519",
                "publicKeyHex": Oydid.multi_decode(doc_pub_mb).first.unpack('H*').first
            }
            if status["private_key"].to_s != ""
                doc_key["privateKeyHex"] = Oydid.multi_decode(status["private_key"]).first.unpack('H*').first
            end
            keys << doc_key
        end

        if !rev_pub_mb.nil?
            rev_key = {
                "kid": Oydid.percent_encode(status["did"]) +  '#key-rev',
                "kms": "local",
                "type": "Ed25519",
                "publicKeyHex": Oydid.multi_decode(rev_pub_mb).first.unpack('H*').first
            }
            if status["revocation_key"].to_s != ""
                rev_key["privateKeyHex"] = Oydid.multi_decode(status["revocation_key"]).first.unpack('H*').first
            end
            keys << rev_key
        end

        keys
    end
end
