class ProvidersController < ApplicationController
    include ApplicationHelper
    include ActionController::MimeResponds

    # respond only to JSON requests
    respond_to :json
    respond_to :html, only: []
    respond_to :xml, only: []

    # Universal-Registrar "DID Provider" endpoints, storing DIDs in the local
    # repository database instead of publishing them to a remote location.
    #
    # The cryptographic material (DID, document, logs, keys) is generated by the
    # oydid gem with `skip_publish: true`; for update/deactivate the current DID
    # state is supplied to the gem in-process via `local_doc`/`local_log`, and the
    # Client-Managed-Secret-Mode (CMSM) intermediate data is persisted through a
    # `LocalCmsmStore`. The resulting document and log entries are persisted with
    # `local_store_did` (shared with DidsController#create).

    # input
    # {
    #     "options": { ... },
    #     "secret":  { ... },
    #     <document fields for CMSM, e.g. "key_hex": "...">
    # }
    def create
        params.permit!
        options = provider_options
        options[:cmsm_store] = LocalCmsmStore.new

        if options[:cmsm]
            # Client-Managed-Secret-Mode: the client provides the public key (and,
            # in phase 2, a signature); private keys never leave the client.
            #
            # the key type has to be settled BEFORE the public key is encoded: the
            # multicodec prefix differs per curve (ed25519-pub 0xed01 vs p256-pub
            # 0x1200), so a hard-coded prefix silently mis-encodes the other curve
            if options[:key_type].nil?
                options[:key_type] = 'p256'
            end
            if options[:key_type] == 'Secp256r1'
                options[:key_type] = 'p256'
            end

            # a session handle continues an already started flow; without one the
            # public key(s) start a new flow
            if options[:cmsm_session].nil?
                options[:cmsm_session] = options[:session]
            end

            doc = params.except(:options, :secret, :provider, :controller, :action)
            doc = JSON.parse(doc.to_json).transform_keys(&:to_sym)
            if !doc[:key_hex].nil?
                pubkey, msg = Oydid.public_key_from_hex(doc[:key_hex], options)
                if pubkey.nil?
                    render json: {"error": "invalid public key in CMSM: " + msg.to_s},
                           status: 400
                    return
                end
                doc[:key] = pubkey
                doc.delete(:key_hex)
            end
            # a second public key makes the revocation key client-managed too;
            # without it the revocation key is generated by this process
            if !doc[:rev_key_hex].nil?
                if doc[:key].nil?
                    render json: {"error": "rev_key_hex requires key_hex in CMSM"},
                           status: 400
                    return
                end
                revpub, msg = Oydid.public_key_from_hex(doc[:rev_key_hex], options)
                if revpub.nil?
                    render json: {"error": "invalid revocation key in CMSM: " + msg.to_s},
                           status: 400
                    return
                end
                doc[:key] = doc[:key].to_s + ":" + revpub
                doc.delete(:rev_key_hex)
            end
            if options[:cmsm_session].to_s == "" && doc[:key].nil?
                render json: {"error": "missing public key in CMSM"},
                       status: 400
                return
            end
        else
            doc = {}
            options[:authentication] = true
            if options[:type] == "ES256"
                options[:key_type] = 'p256'
                options[:keyAgreement] = true
            else
                options[:key_type] = 'ed25519'
                options[:x25519_keyAgreement] = true
            end
        end

        status, msg = Oydid.create(doc, options)

        if status.nil?
            render json: {"error": msg},
                   status: client_error?(msg) ? 400 : 500
            return
        elsif msg == "cmsm"
            # intermediate CMSM phase: the data has been persisted by the gem via
            # LocalCmsmStore under the returned session handle; the response says
            # which value the client has to sign and with which key
            render json: status,
                   status: 201
            return
        end

        did_hash = local_identifier(status["did"])
        ok, store_msg = local_store_did(did_hash, status["doc"], status["log"])
        if !ok
            render json: {"error": store_msg},
                   status: store_msg == KEY_IN_USE_ERROR ? 400 : 500
            return
        end

        # the flow is complete - the intermediate data authorises operations on
        # this DID and must not outlive the operation
        if options[:cmsm_session].to_s != ""
            options[:cmsm_store].delete(options[:cmsm_session])
        end

        retVal = {
            "did": Oydid.percent_encode(status["did"]),
            "controllerKeyId": Oydid.percent_encode(status["did"]) +  '#key-doc',
            "keys": create_keys(status, options),
            "services": []
        }
        # In CMSM the revocation record is the only artefact the client cannot
        # rebuild later: its signature was made by a key this process never saw,
        # and a secure element does not have to sign deterministically. Without
        # it the DID can neither be updated nor revoked, so hand it out - it is
        # a log entry, not a secret.
        if options[:cmsm]
            retVal["log_revoke"] = status["revocation_log"]
        end
        render json: retVal.to_json,
               status: 200
    end

    # input
    # {
    #     "args":        { "did": "did:oyd:..." },
    #     "didDocument": { ... },          # optional (client-managed update)
    #     "options":     { ... },
    #     "secret":      { ... }
    # }
    def update
        old_did = (params[:args][:did] rescue nil)
        didDocument = params[:didDocument]
        params.permit!
        options = provider_options
        options[:cmsm_store] = LocalCmsmStore.new

        if options[:cmsm]
            if options[:cmsm_session].nil?
                options[:cmsm_session] = options[:session]
            end
            # from the second phase on the client sends nothing but the session
            # and one signature - which DID is being updated comes from the flow
            if old_did.to_s == "" && options[:cmsm_session].to_s != ""
                stored = options[:cmsm_store].get(options[:cmsm_session])
                old_did = stored["did_old"] if stored.is_a?(Hash)
                # dag_update sets currentDID["did"] to the bare log hash, so what
                # the gem persisted as did_old carries no method prefix
                if old_did.to_s != "" && !old_did.to_s.start_with?("did:oyd:")
                    old_did = "did:oyd:" + old_did.to_s
                end
            end
        end
        if old_did.to_s == ""
            render json: {"error": "missing DID"},
                   status: 400
            return
        end

        old_doc, old_log = load_local_state(old_did)
        if old_doc.nil?
            render json: {"error": "unknown DID"},
                   status: 404
            return
        end
        options[:local_doc] = old_doc
        options[:local_log] = old_log
        # dag_update walks the whole update chain and resolves each document by
        # its own hash - local_doc alone cannot serve that, so hand it the store
        options[:local_store] = LocalDidStore.new
        options[:key_type] = key_type_for(old_doc, options[:key_type])

        if options[:cmsm]
            cmsm_update(old_did, didDocument, options)
            return
        end

        did_obj = JSON.parse((didDocument || {}).to_json) rescue {}
        did_obj = {} if did_obj.nil?
        if did_obj.is_a?(Hash) && did_obj["@context"] == "https://www.w3.org/ns/did/v1"
            did_obj = Oydid.fromW3C(did_obj, options)
        end

        if did_obj.is_a?(Hash) && !did_obj["key"].nil? &&
           !options[:log_revoke].nil? && !options[:log_update].nil? && !options[:log_terminate].nil?
            # client-managed update: caller supplies pre-signed log records
            old_doc_pubkey = old_doc["key"].split(":")[0].to_s
            success, vmsg = Oydid.verify(options[:log_update]["doc"], options[:log_update]["sig"], old_doc_pubkey)
            if !success
                render json: {"error": "invalid input data (update log has invalid signature)"},
                       status: 400
                return
            end
            did = "did:oyd:" + Oydid.multi_hash(Oydid.canonical(did_obj), options).first
            logs = [options[:log_revoke], options[:log_update], options[:log_terminate]]
            ok, store_msg = local_store_did(local_identifier(did), did_obj, logs)
            if !ok
                render json: {"error": store_msg},
                       status: 500
                return
            end
            status = {
                "did" => did,
                "doc" => did_obj,
                "log" => logs,
                "private_key" => "",
                "revocation_key" => ""
            }
        else
            status, msg = Oydid.update(did_obj, old_did, options)
            if status.nil?
                render json: {"error": msg},
                       status: 500
                return
            end
            ok, store_msg = local_store_did(local_identifier(status["did"]), status["doc"], status["log"])
            if !ok
                render json: {"error": store_msg},
                       status: 500
                return
            end
        end

        retVal = {
            "did": Oydid.percent_encode(status["did"]),
            "provider": request.base_url,
            "controllerKeyId": Oydid.percent_encode(status["did"]) +  '#key-doc',
            "keys": update_keys(status),
            "services": []
        }
        render json: retVal.to_json,
               status: 200
    end

    # input
    # {
    #     "identifier": { "did": "did:oyd:..." },
    #     "options":    { ... },
    #     "secret":     { ... }
    # }
    def deactivate
        did = params[:identifier][:did]
        params.permit!
        options = provider_options
        if options[:old_doc_pwd].nil? && !options[:doc_pwd].nil?
            options[:old_doc_pwd] = options[:doc_pwd]
        end
        if options[:old_rev_pwd].nil? && !options[:rev_pwd].nil?
            options[:old_rev_pwd] = options[:rev_pwd]
        end

        old_doc, old_log = load_local_state(did)
        if old_doc.nil?
            render json: {"error": "unknown DID"},
                   status: 404
            return
        end
        options[:local_doc] = old_doc
        options[:local_log] = old_log
        options[:local_store] = LocalDidStore.new
        options[:key_type] = key_type_for(old_doc, options[:key_type])

        # With skip_publish the gem returns the revocation log entry instead of
        # publishing it, so it can be persisted locally. Both modes go through
        # here: with the controller keys from `secret`, or - when the client
        # holds them and cannot sign here - with the record it kept, which the
        # gem verifies against the current document before handing it back.
        revoc_log, msg = Oydid.revoke(did, options)
        if revoc_log.nil?
            render json: {"error": msg},
                   status: client_error?(msg) ? 400 : 500
            return
        end

        ok, store_msg = local_store_did(local_identifier(did), old_doc, [revoc_log])
        if !ok
            render json: {"error": store_msg},
                   status: 500
            return
        end

        render json: {"did": Oydid.percent_encode(did), "success": true}.to_json,
               status: 200
    end

    private

    # Client-Managed-Secret-Mode update. Phase 1 carries the new DID document,
    # the new public key(s) and the revocation record of the current document;
    # every later phase carries only the session and one signature.
    def cmsm_update(old_did, didDocument, options)
        if options[:cmsm_session].to_s == ""
            did_obj = JSON.parse((didDocument || {}).to_json) rescue {}
            did_obj = {} if !did_obj.is_a?(Hash)
            if did_obj["@context"] == "https://www.w3.org/ns/did/v1"
                did_obj = Oydid.fromW3C(did_obj, options)
            end

            key, err = cmsm_public_keys(options)
            if key.nil?
                render json: {"error": err}, status: 400
                return
            end
            did_obj["key"] = key

            if options[:log_revoke_old].nil?
                render json: {"error": "CMSM update requires the revocation record of the current document (log_revoke_old)"},
                       status: 400
                return
            end
        else
            did_obj = {}
        end

        status, msg = Oydid.update(did_obj, old_did, options)
        if status.nil?
            render json: {"error": msg},
                   status: client_error?(msg) ? 400 : 500
            return
        elsif msg == "cmsm"
            render json: status,
                   status: 201
            return
        end

        ok, store_msg = local_store_did(local_identifier(status["did"]), status["doc"], status["log"])
        if !ok
            render json: {"error": store_msg},
                   status: 500
            return
        end
        options[:cmsm_store].delete(options[:cmsm_session]) if options[:cmsm_session].to_s != ""

        render json: {
            "did": Oydid.percent_encode(status["did"]),
            "did_old": Oydid.percent_encode(old_did),
            "provider": request.base_url,
            "controllerKeyId": Oydid.percent_encode(status["did"]) + '#key-doc',
            "keys": update_keys(status),
            "services": [],
            # replaces the record the client kept for the previous document
            "log_revoke": status["revocation_log"]
        }.to_json, status: 200
    end

    # turn the hex-encoded public keys of a CMSM request into the "key" field of
    # a DID document ("<doc>" or "<doc>:<rev>")
    def cmsm_public_keys(options)
        key_hex = params[:key_hex]
        rev_hex = params[:rev_key_hex]
        if key_hex.nil?
            return [nil, "missing public key in CMSM"]
        end
        pubkey, msg = Oydid.public_key_from_hex(key_hex, options)
        if pubkey.nil?
            return [nil, "invalid public key in CMSM: " + msg.to_s]
        end
        return [pubkey, nil] if rev_hex.nil?

        revpub, msg = Oydid.public_key_from_hex(rev_hex, options)
        if revpub.nil?
            return [nil, "invalid revocation key in CMSM: " + msg.to_s]
        end
        [pubkey + ":" + revpub, nil]
    end

    # build option hash from request, force local in-process storage
    def provider_options
        options = params[:options] || {}
        secret = params[:secret] || {}
        options = options.to_hash.merge(secret.to_hash).transform_keys(&:to_sym)
        options[:return_secrets] = true
        options[:skip_publish] = true
        options
    end

    # strip the "did:oyd:" prefix and any location suffix
    def local_identifier(did)
        (did.to_s.delete_prefix("did:oyd:").split(LOCATION_PREFIX).first rescue did.to_s)
    end

    # resolve current DID document + raw log array from the local database
    def load_local_state(did)
        did_hash = local_identifier(did)
        _did, doc = local_retrieve_document(did_hash)
        return [nil, nil] if doc.nil?
        [doc, local_retrieve_log(did_hash)]
    end

    # gem messages that describe a problem with the request rather than with the
    # server - these deserve 400 instead of 500
    CLIENT_ERRORS = [
        "unknown or expired CMSM session",
        "missing signature in CMSM flow (sig)",
        "invalid persisted data in CMSM flow"
    ].freeze

    def client_error?(msg)
        msg = msg.to_s
        return true if CLIENT_ERRORS.include?(msg)
        # anything the gem reports about a CMSM input or about a revocation
        # record supplied by the client is a bad request, not a server fault.
        # "log_revoke" covers "log_revoke_old" as well. Matching on the text
        # rather than on a fixed list keeps this working when the gem gains
        # further messages.
        msg.start_with?("CMSM ") || msg.include?("log_revoke")
    end

    # curve used for keys generated during an update/deactivate. The gem needs
    # options[:key_type] whenever it has to generate a key pair itself and does
    # `options[:key_type] + '-priv'` unguarded, so a missing value crashes with
    # NoMethodError. Default to the curve the existing DID already uses instead
    # of a fixed one - an update must not silently switch curves.
    def key_type_for(old_doc, requested)
        requested = 'p256' if requested.to_s == 'Secp256r1'
        return requested if requested.to_s != ''

        old_key_type = Oydid.get_keytype(old_doc["key"].split(":")[0]) rescue nil
        old_key_type.to_s == 'p256-pub' ? 'p256' : 'ed25519'
    end

    # raw hex of a Multibase-encoded public key (2-byte multicodec varint prefix)
    def pubkey_hex(key_mb)
        Oydid.multi_decode(key_mb).first.unpack('CCa*').last.bytes.pack('C*').unpack1('H*')
    end

    # raw hex of a Multibase-encoded private key ([uint16 code][uint8 len][key])
    def privkey_hex(key_mb)
        Oydid.multi_decode(key_mb).first.unpack('SCa*').last.bytes.pack('C*').unpack1('H*')
    end

    # build the universal-registrar "keys" array for a freshly created DID
    def create_keys(status, options)
        keys = []
        if options[:type] == "ES256" || options[:key_type] == "p256"
            if !status["private_key"].nil?
                keyJwk = Oydid.private_key_to_jwk(status["private_key"]).first
                keys << {
                    "kid": Oydid.percent_encode(status["did"]) +  '#key-doc',
                    "kms": "local",
                    "type": "ES256",
                    "jwk": keyJwk
                }
            end
        else
            # in Client-Managed-Secret-Mode the private keys never reach this
            # process and the document carries no derived keyAgreement entry, so
            # every private part is emitted only when it is actually present
            doc_pub_mb = status["doc"]["key"].split(":")[0] rescue nil
            rev_pub_mb = status["doc"]["key"].split(":")[1] rescue nil
            x25519_mb  = begin
                ka = status["doc"]["doc"]["keyAgreement"].first
                ka[:publicKeyMultibase] || ka["publicKeyMultibase"]
            rescue StandardError
                nil
            end

            # document key
            if !doc_pub_mb.nil?
                pubKeyHex = pubkey_hex(doc_pub_mb)
                doc_key = {
                    "kid": Oydid.percent_encode(status["did"]) +  '#key-doc',
                    "kms": status["private_key"].to_s == "" ? "external" : "local",
                    "type": "Ed25519",
                    "publicKeyHex": pubKeyHex
                }
                if status["private_key"].to_s != ""
                    doc_key["privateKeyHex"] = privkey_hex(status["private_key"]) + pubKeyHex
                end
                keys << doc_key
            end

            # revocation key
            if !rev_pub_mb.nil?
                pubKeyHex = pubkey_hex(rev_pub_mb)
                rev_key = {
                    "kid": Oydid.percent_encode(status["did"]) +  '#key-rev',
                    "kms": status["revocation_key"].to_s == "" ? "external" : "local",
                    "type": "Ed25519",
                    "publicKeyHex": pubKeyHex
                }
                if status["revocation_key"].to_s != ""
                    rev_key["privateKeyHex"] = privkey_hex(status["revocation_key"]) + pubKeyHex
                end
                keys << rev_key
            end

            # x25519 key agreement (derived from the private document key, so it
            # only exists when this process generated the keys itself)
            if !x25519_mb.nil? && status["private_key"].to_s != ""
                pubKeyHex = pubkey_hex(x25519_mb)
                keys << {
                    "kid": Oydid.percent_encode(status["did"]) +  '#key-doc-x25519',
                    "kms": "local",
                    "type": "X25519",
                    "publicKeyHex": pubKeyHex,
                    "privateKeyHex": privkey_hex(status["private_key"]) + pubKeyHex
                }
            end
        end
        keys
    end

    # build the "keys" array for an updated DID; omits private parts when the
    # private keys are managed by the client (not known to the repository)
    def update_keys(status)
        keys = []
        doc_pub_mb = status["doc"]["key"].split(":")[0] rescue nil
        rev_pub_mb = status["doc"]["key"].split(":")[1] rescue nil

        if !doc_pub_mb.nil?
            doc_key = {
                "kid": Oydid.percent_encode(status["did"]) +  '#key-doc',
                "kms": "local",
                "type": "Ed25519",
                "publicKeyHex": Oydid.multi_decode(doc_pub_mb).first.unpack('H*').first
            }
            if status["private_key"].to_s != ""
                doc_key["privateKeyHex"] = Oydid.multi_decode(status["private_key"]).first.unpack('H*').first
            end
            keys << doc_key
        end

        if !rev_pub_mb.nil?
            rev_key = {
                "kid": Oydid.percent_encode(status["did"]) +  '#key-rev',
                "kms": "local",
                "type": "Ed25519",
                "publicKeyHex": Oydid.multi_decode(rev_pub_mb).first.unpack('H*').first
            }
            if status["revocation_key"].to_s != ""
                rev_key["privateKeyHex"] = Oydid.multi_decode(status["revocation_key"]).first.unpack('H*').first
            end
            keys << rev_key
        end

        keys
    end
end
