source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails'
gem 'puma', '>= 3.12.2'
gem 'rack-cors', ">= 1.0.4", require: 'rack/cors'
gem 'rbnacl'
gem 'httparty'
gem 'responders'
gem 'sprockets', '~> 3.7'
gem 'ed25519'
gem 'dag'
gem 'multibases'
gem 'multihashes'
gem 'multicodecs'
gem 'json-canonicalization', '~> 0.3.0'
gem 'oydid'
gem 'bootsnap'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  # gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'better_errors'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'annotate'
end
