source 'https://rubygems.org'

ruby '3.2.8'

gem 'rails', "~> 7.2"
gem 'sqlite3'
gem 'pg'
gem 'puma'
gem 'rack-cors', ">= 1.0.4", require: 'rack/cors'
gem 'rbnacl'
gem 'httparty'
gem 'responders'
gem 'rswag'
# gem 'pagy'
gem 'ed25519'
gem 'multibases'
gem 'multihashes'
gem 'multicodecs'
gem 'json-canonicalization'
gem 'oydid'
gem 'doorkeeper'
gem 'sass-rails', '>= 6'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :windows]
  gem 'rspec-rails'
end

group :development do
  # gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'better_errors'
  gem 'rails-erd'
  gem 'annotate'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
  # gem 'annotate'
end
