source 'https://rubygems.org'

ruby '2.5.9'

gem 'rails', '~> 5.2.5'
gem 'sqlite3', '~> 1.3.6'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '>= 3.12.2'
gem 'rack-cors', ">= 1.0.4", require: 'rack/cors'
gem 'rbnacl'
gem 'httparty'
gem 'responders'
gem 'sprockets', '~> 3.7'
gem 'rswag'
gem 'pagy', '~> 3.5'
gem 'ed25519'
gem 'dag'
gem 'multibases'
gem 'multihashes'
gem 'multicodecs'
gem 'json-canonicalization', '~> 0.2.1'
gem 'oydid'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'better_errors'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'annotate'
end
