source 'https://rubygems.org'

ruby '3.1.3'

gem 'rails', '~> 7.0.4'
gem 'puma'
gem 'rack-cors', ">= 1.0.4", require: 'rack/cors'
gem 'responders'
gem 'bootsnap'
gem 'oydid'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0' # must be >=3 for Rails 7.x
  gem 'annotate'
end
