source 'https://rubygems.org'

ruby '2.5.9'

gem 'rails', '~> 5.2.5'
gem 'puma', '>= 3.12.2'
gem 'rack-cors', ">= 1.0.4", require: 'rack/cors'
gem 'bootsnap'
gem 'oydid'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'better_errors'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'annotate'
end
