# Adapter that lets the oydid gem read and write the intermediate data of a
# Client-Managed-Secret-Mode (CMSM) flow in the local database (Cmsm model)
# instead of posting it to a remote location.
#
# The gem calls #get(session) (in check_cmsm) and #set(session, payload)
# (in persist_cmsm) when it receives this object via options[:cmsm_store].
# The session handle is generated by the gem.
class LocalCmsmStore
    # returns the persisted payload as a Hash, or nil when the session is
    # unknown or has expired
    def get(session)
        Cmsm.sweep
        rec = Cmsm.find_by_session(session)
        return nil if rec.nil?
        if rec.expired?
            rec.destroy
            return nil
        end
        JSON.parse(rec.payload) rescue nil
    end

    # persists the payload (Hash) for the given session handle
    def set(session, payload)
        payload = JSON.parse(payload.to_json) rescue {}
        rec = Cmsm.find_by_session(session) || Cmsm.new(session: session)
        rec.session = session
        rec.pubkey  = payload["publicKey"]
        rec.payload = payload.to_json
        rec.save
        [true, ""]
    end

    # drop a finished flow - nothing in it may outlive the operation
    def delete(session)
        Cmsm.where(session: session).destroy_all
    end
end
