apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oydid-tls
  annotations:
    cert-manager.io/issuer: "{{YOUR CERT-MANAGER}}"
spec:
  secretName: oydid-tls
  issuerRef:
    group: cert-manager.io
    name: {{YOUR CERT-MANAGER}}
    kind: Issuer
  dnsNames:
  - '{{YOUR OYDID REPOSITORY HOSTNAME}}'
