apiVersion: apps/v1
kind: Deployment
metadata:
  name: oydid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oydid
  template:
    metadata:
      labels:
        app: oydid
    spec:
      containers:
      - name: oydid
        image: oydeu/oydid-base:latest
        ports:
        - containerPort: 3000
        env:
          - name: LANG
            value: C.UTF-8
          - name: RAILS_LOG_TO_STDOUT
            value: "TRUE"
          - name: RAILS_SERVE_STATIC_FILES
            value: "TRUE"
          - name: RAILS_ENV
            value: production
          - name: DEFAULT_VC_OAUTH_APP
            value: "oydid-vc"
          - name: DB_HOST
            value: {{YOUR POSTGRESQL-CLUSTER HOST}}
          - name: DB_NAME
            value: oydid_production
          - name: DB_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{YOUR SECRETS}}
                key: oydid-db-passwd
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{YOUR SECRETS}}
                key: secret-key-base