# This workflow runs continuous CI across different versions of ruby on all branches and pull requests to develop.

name: CI
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  tests:
    name: Ruby ${{ matrix.ruby }}
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    runs-on: ubuntu-latest
    env:
      CI: true
      ALLOW_FAILURES: ${{ endsWith(matrix.ruby, 'head') }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        working-directory: ruby-gem
        run: bundle install --jobs 4 --retry 3
      - name: Run tests
        working-directory: ruby-gem
        run: ruby --version; bundle exec rspec spec || $ALLOW_FAILURES
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        if: "matrix.ruby == '2.6'"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./ruby-gem/coverage/lcov.info"
          base-path: "./ruby-gem/lib/"
